### ISSUE TITLE
`-c` param related-error:  java.lang.NullPointerException

### ISSUE THREAD

**Issue by hiiiyilingzhang** [sa501428/hic-emt#2]
Hi hic-emt dev team, 

Thanks for the nice tools! 
I've got an error when I want to extract chromosome 1-22 (`straw.getChromosomes()` shows it has: All,1-22,X,Y,MT) using the following code:

```
java -Xmx15g -jar hic_emt.jar excise -r 5000 -c 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22 --cleanup GM12878_combined.hic GM_22chr_emt
```

Output was like:
```
Reading file: GM12878_combined.hic
HiC file version: 7
Exception in thread "main" java.lang.NullPointerException
        at javastraw.reader.basics.ChromosomeHandler.inferGenomeId(ChromosomeHandler.java:287)
        at javastraw.reader.basics.ChromosomeHandler.<init>(ChromosomeHandler.java:53)
        at javastraw.reader.basics.ChromosomeHandler.<init>(ChromosomeHandler.java:47)
        at javastraw.tools.HiCFileTools.stringToChromosomes(HiCFileTools.java:191)
        at emt.clt.tools.Excise.run(Excise.java:58)
        at emt.Tools.main(Tools.java:75)
```

Seems like it can't detect `-c` input? Cause when I run without `-c`, it works perfectly.

Another question, how can I know the number of Hi-C contacts from a .hic file? Sry it's not hic-emt related, it would be of great help if you can drop me some hints.

Thanks
Yiling

**Comment by brauliobonilla** [comment]
Hello,

Thanks for this great tool.

I keep getting an error that I'm not sure how to address:

`java -Xmx20g -jar /home/braulio/lab/analisis/hic/Hi-C_EMT/hic_emt.jar excise --subsample 1312476019 /media/braulio/Braulio/hic/juicer/GFP/GFP/mega/inter_30.hic subsample_folder inter_30_1.3.hic
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Aiming to retain ~1312476019/2414513412 
Ratio: 0.5435778540210486
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
...WARN [2023-07-15T20:21:39,752]  [Globals.java:138] [main]  Development mode is enabled
Using 1 CPU thread(s) for primary task
Using 1 CPU thread(s) for secondary task
Exception in thread "main" java.lang.NoSuchFieldError: useIteratorDontPutAllInRAM
	at hic.HiCGlobals.setMatrixZoomDataRAMUsage(HiCGlobals.java:75)
	at hic.tools.clt.old.PreProcessing.readArguments(PreProcessing.java:154)
	at hic.tools.HiCTools.main(HiCTools.java:82)
	at emt.main.FileBuildingMethod.buildNewHiCFile(FileBuildingMethod.java:52)
	at emt.main.FileBuildingMethod.tryToBuild(FileBuildingMethod.java:58)
	at emt.clt.tools.Excise.run(Excise.java:71)
	at emt.Tools.main(Tools.java:75)
`
The files that I am using are V9 and they do have SCALE. Do you know what could cause this?
I tried the cluster using module load java/1.8.0_121 with the same result

Thank you!
Braulio
